- hosts: all
  roles:
    - install-jdk
    - install-maven
    - role: maven
      vars:
        # TODO: support more
        maven_pom_dir: "{{ java_libraries[0].context }}"
        maven_phases: ["install"]
