- hosts: all
  roles:
    - role: use-buildset-registry
    - role: clear-firewall
    - role: ensure-docker
    - role: ensure-minikube
    - role: ensure-helm
  tasks:
    - name: Start minikube
      command: minikube start --cpus max --memory max --container-runtime cri-o

    - name: Replace minikube registries.conf
      block:
        - name: Copy registries.conf from the host to minikube
          command: minikube cp /etc/containers/registries.conf /etc/containers/registries.conf

        - name: Restart minikube crio daemon
          command: minikube ssh sudo systemctl restart crio

        - name: Wait for minikube k8s API to be back up
          command: kubectl get node
          register: _result
          until: _result is not failed
          retries: 30
          delay: 10
