- hosts: all
  tasks:
    - name: Pull helm charts deps
      command: "helm dependency build {{ helm_chart }}"
      vars:
        helm_chart: "{{ zj_item.value }}"
      loop: "{{ helm_charts | dict2items }}"
      loop_control:
        loop_var: 'zj_item'
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Install helm charts
      command: "helm install {{ helm_release_name }} {{ helm_chart }}"
      vars:
        helm_release_name: "{{ zj_item.key }}"
        helm_chart: "{{ zj_item.value }}"
      loop: "{{ helm_charts | dict2items }}"
      loop_control:
        loop_var: 'zj_item'
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Wait for the deployments
      command: kubectl wait --for=condition=Available --timeout=300s deployment --all

    - name: Wait for the remaining resources
      include_role:
        name: wait-for-pods

    - name: Check pod restarts after helm chart installations
      include_role:
        name: check-pod-restarts
