- name: Download minikube
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube-linux-amd64
    dest: /tmp/minikube
    mode: 0755

- name: Install minikube
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/minikube
    dest: /usr/local/bin/minikube
    mode: "0755"

- name: Install kubectl from minikube
  become: true
  ansible.builtin.file:
    src: /usr/local/bin/minikube
    dest: /usr/local/bin/kubectl
    state: link
